# Generated by Django 5.0.3 on 2024-03-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.CharField(max_length=255)),
                ("detailed", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "expense_account",
                    models.CharField(default=None, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                ("item_id", models.CharField(max_length=255, unique=True)),
                ("access_token", models.CharField(max_length=255)),
                ("cursor", models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaidSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "ticker_symbol",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(max_length=255)),
                (
                    "market_identifier_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_cash_equivalent", models.BooleanField()),
                ("isin", models.CharField(blank=True, max_length=255, null=True)),
                ("cusip", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaidInvestmentTransactionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("subtype", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("type", "subtype")},
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=255, null=True)),
                (
                    "beancount_name",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("plaid_id", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("depository", "Depository"),
                            ("credit", "Credit"),
                            ("loan", "Loan"),
                            ("investment", "Investment"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="transactions.plaiditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaidInvestmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cancel_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "investment_transaction_id",
                    models.CharField(max_length=255, unique=True),
                ),
                (
                    "iso_currency_code",
                    models.CharField(
                        blank=True, default="USD", max_length=255, null=True
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.plaidinvestmenttransactiontype",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.plaidsecurity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaidTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("datetime", models.DateTimeField(default=None, null=True)),
                ("authorized_date", models.DateField(default=None, null=True)),
                ("authorized_datetime", models.DateTimeField(default=None, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "merchant_name",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("website", models.CharField(default=None, max_length=255, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "check_number",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                (
                    "personal_finance_confidence",
                    models.CharField(
                        choices=[
                            ("VERY_HIGH", "Very High"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("pending", models.BooleanField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transactions.account",
                    ),
                ),
                (
                    "personal_finance_category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transactions.financecategory",
                    ),
                ),
            ],
        ),
    ]
