# Generated by Django 5.0.3 on 2024-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
