# Generated by Django 5.0.3 on 2024-04-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_account_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaidinvestmenttransaction",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plaidinvestmenttransaction",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
