# Generated by Django 5.0.6 on 2024-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_plaidinvestmenttransaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_file',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
